spring.application.name=mehedi-portfolio

# Server
server.port=8080

# CORS
cors.allowed-origins=http://localhost:3000

# Logging
logging.level.com.mehedi.portfolio=INFO
logging.level.org.springframework.web=DEBUG

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=idehemnassah@gmail.com
spring.mail.password=nyiz xhxy yiwx srxy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

portfolio.email.to=idehemnassah@gmail.com